In [1]:
import pandas as pd
data = pd.read_csv("data/raw_data_0317.csv")
data

,Unnamed: 0,uid,page_id,text_sequences,eye_tracking_sequences,labels
0,0,ys,1226,"[[0, 'A', 330, 95, 32, 52], [1, 'judge', 362, ...","[[499, 499, 15], [499, 497, 10470], [497, 490,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,1,ys,1227,"[[0, 'And', 330, 95, 63, 52], [1, 'both', 393,...","[[615, 279, 169376], [696, 224, 169411], [776,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
2,2,wangchenyu,1236,"[[0, ""Canada's"", 330, 95, 118, 52], [1, 'emerg...","[[500, 500, 16], [500, 499, 10360], [502, 497,...","[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,3,wangchenyu,1237,"[[0, 'NASA', 330, 95, 83, 52], [1, 'is', 413, ...","[[1347, 1105, 207856], [1401, 1049, 208345], [...","[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,4,luqi,1247,"[[0, 'Reports', 330, 95, 105, 52], [1, 'from',...","[[500, 499, 16], [499, 498, 10663], [497, 492,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ..."
...,...,...,...,...,...,...
209,209,bxy,2787,"[[0, 'In', 330, 95, 37, 52], [1, 'a', 367, 95,...","[[979, 367, 238846], [854, 305, 239281], [807,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
210,210,qxy,2788,"[[0, 'Enlightening', 330, 95, 166, 52], [1, 'c...","[[499, 500, 35], [500, 496, 1187], [508, 484, ...","[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
211,211,qxy,2789,"[[0, 'The', 330, 95, 58, 52], [1, 'alliances',...","[[1292, 725, 97283], [1185, 574, 97685], [1114...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
212,212,qxy,2790,"[[0, 'W', 330, 95, 40, 52], [1, 'V', 370, 95, ...","[[500, 499, 14], [498, 499, 1125], [491, 503, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
213,213,qxy,2791,"[[0, 'We', 330, 95, 53, 52], [1, 'should', 383...","[[1148, 780, 93190], [1144, 784, 93222], [1090...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [17]:
page_skip_info = {}
for i, row in data.iterrows():
    page_skip_info[row['page_id']] = len(row['eye_tracking_sequences'])/len(row['text_sequences'])

fixations_per_words = [val for key, val in page_skip_info.items()]
fixations_per_words.sort()

min_no_skip_thredhold = fixations_per_words[int(len(fixations_per_words)*0.4)]
max_skip_thredhold = fixations_per_words[int(len(fixations_per_words)*0.6)]

min_no_skip_thredhold, max_skip_thredhold

skip_pages = [key for key, val in page_skip_info.items() if val < max_skip_thredhold]
not_skip_pages = [key for key, val in page_skip_info.items() if val > min_no_skip_thredhold]
len(skip_pages), len(not_skip_pages)

(128, 128)

In [18]:
data[data['page_id'].isin(skip_pages)].to_csv('data/skip_data.csv')
data[data['page_id'].isin(not_skip_pages)].to_csv('data/not_skip_data.csv')