In [2]:
import pandas as pd
not_corrected_data_skip = pd.read_csv("data/final_data/word-feature-without-correct-skip_1.csv") # 无纠正跳读
not_corrected_data_skip

,Unnamed: 0,exp_id,article_id,time,page_id,user,sentence_id,word,word_understand,sentence_understand,mind_wandering,reading_times,number_of_fixations,fixation_duration,fixation_duration_div_syllable,fixation_duration_div_length,fixation_duration_diff,number_of_fixations_diff,reading_times_diff
0,273,585,12,0,1227,ys,0,And,1,1,0,0,0,0,0.000000,0.000000,0,0,0
1,274,585,12,0,1227,ys,0,both,1,1,0,1,2,1011,1011.000000,252.750000,1011,2,1
2,275,585,12,0,1227,ys,0,he,1,1,0,0,0,0,0.000000,0.000000,-1011,-2,-1
3,276,585,12,0,1227,ys,0,and,1,1,0,1,2,471,471.000000,157.000000,471,2,1
4,277,585,12,0,1227,ys,0,Nadal,1,1,0,0,0,0,0.000000,0.000000,-471,-2,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9722,40237,1885,39,0,2787,bxy,0,the,1,1,1,1,1,500,500.000000,166.666667,-196,-1,0
9723,40238,1885,39,0,2787,bxy,0,Italian,1,1,1,1,1,452,226.000000,64.571429,-48,0,0
9724,40239,1885,39,0,2787,bxy,0,dictator,1,1,1,0,0,0,0.000000,0.000000,-452,-1,-1
9725,40240,1885,39,0,2787,bxy,0,Benito,1,1,1,2,2,481,160.333333,80.166667,481,2,2
9726,40241,1885,39,0,2787,bxy,0,Mussolini,1,1,1,1,2,589,196.333333,65.444444,108,0,-1

In [ ]:
import pandas as pd

# 读取 csv 文件
data = pd.read_csv('your_file.csv')

# 定义要处理的眼动指标列
eye_movement_columns = ['number_of_fixations', 'fixation_duration', 'reading_times']

# 计算左右各两个值的平均值和最大值，并添加为新列
for column in eye_movement_columns:
    data[f'{column}_avg_left_two'] = data[column].rolling(window=2).mean().shift(-1)
    data[f'{column}_max_left_two'] = data[column].rolling(window=2).max().shift(-1)
    data[f'{column}_avg_right_two'] = data[column].rolling(window=2).mean().shift(1)
    data[f'{column}_max_right_two'] = data[column].rolling(window=2).max().shift(1)

# 将处理后的数据写入新的 csv 文件
data.to_csv('new_file.csv', index=False)